version: "2"
services:
  server:
    build: .
    # restart: always
    environment:
      - HOST=localhost
      - PORT=8082
      - MONGO_URL=mongo:27017
      - MONGO_DATABASE=test
      - NODE_ENV=prod
    networks:
      - proxy
    ports:
      - 8082:8082
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017:27017"
    networks:
      - proxy
    volumes:
      - "mongo-data:/data/db"
    restart: always
volumes:
  mongo-data:

networks:
  proxy:
    external: true
