version: "2"
services:
  server:
    image: koishii/ecomerce-example
    restart: always
    environment:
      - HOST=localhost
      - PORT=8082
      - MONGO_URL=mongo:27017
      - MONGO_DATABASE=test
      - NODE_ENV=prod
    labels:
      - traefik.backend=ecomerce
      - traefik.frontend.rule=Host:ee.yuyuko.me
      - traefik.docker.network=proxy
      - traefik.port=8082
    networks:
      - proxy
    ports:
      - 8082:8082
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
    networks:
      - proxy
    volumes:
      - "mongo-data:/data/db"
    restart: always
volumes:
  mongo-data:

networks:
  proxy:
    external:
      name: proxy
