version: "3.6"
services:
  server:
    build: .
    # image: koishii/ecomerce-example
    environment:
      - HOST=localhost
      - PORT=8082
      - MONGO_URL=user:password@mongo:27017/test?authSource=admin
      - NODE_ENV=prod
    depends_on:
      - mongo
    ports:
      - 8082:8082
  mongo:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data2:/data/db"


volumes:
  mongo-data2:
